/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Wrapping Paper": "包装纸",
    ". Auto-saving has been enabled. Check the console for more details, and consider sharing it with the developers on discord.": ". 已启用自动保存。 查看控制台以获取更多详细信息，并考虑在 discord 上与开发人员共享。",
    "Advent Incremental": "降临增量",
    "Close": "关闭",
    "Cloth": "衣服",
    "Coal": "煤",
    "Congratulations!": "恭喜你！",
    "Day": "天数",
    "Elf Training": "精灵训练",
    "This game is intended to be played as an advent calendar, but it is currently not December. In order to allow players to still enjoy this game, there is a field in the options menu to ignore the month and/or day. You can also change that setting here:": "这款游戏本打算作为降临节日历进行，但目前还不是12月。为了让玩家仍然可以享受这款游戏，选项菜单中有一个字段可以忽略月份和/或日期。您也可以在此处更改该设置：",
    "Toys": "玩具",
    "Saves Manager": "存档管理",
    "Ribbons": "缎带",
    "Pause game": "暂停游戏",
    "New Game": "新游戏",
    "Trees": "树",
    "Ignore": "忽略",
    "Ignore Month and Day": "忽略月和天",
    "Ignore Month": "忽略月",
    "Ignore Date": "忽略日期",
    "Import Save": "导入存档",
    "It's not December": "现在不是十二月",
    "Letters": "信件",
    "Metal": "金属",
    "The Workshop": "车间",
    "- Advent Incremental -": "- 降临增量 -",
    "Allow playing the game not as an advent calendar": "允许玩游戏而不是作为降临节日历",
    "And last but not least, a massive thanks to everyone who played and provided feedback on the game.": "最后但同样重要的是，非常感谢所有参与游戏并提供游戏反馈的人。",
    "Auto-saving is disabled while between days": "在几天之间禁用自动保存",
    "Autosave": "自动保存",
    "Boxes": "盒子",
    "Create Save": "创建保存",
    "Credits": "鸣谢",
    "Dec": "12",
    "Don't Ignore": "不忽略",
    "Plant up to": "一次性种植",
    "Present Packing": "礼物包装",
    "Oh no! Santa forgot about Christmas and it's only 25 days away! He's asked for your help due to your history getting large quantities of things in short amounts of time. Unfortunately you're really starting from scratch here - let's start with getting wood, which you'll need for everything from building workshops to wrapping paper to many of the toys themselves!": "不好了！ 圣诞老人忘记了圣诞节，离圣诞节只有 25 天了！ 由于您过去曾在短时间内获得大量物品，因此他向您寻求帮助。 不幸的是，你真的是从头开始——让我们从获取木材开始，从建造车间到包装纸再到许多玩具本身，你都需要木材！",
    "at once!": "！",
    "Automated Knives": "自动刀",
    "Automated Spade": "自动铲",
    "Automatically save the game every second or when the game is closed.": "每秒或游戏关闭时自动保存游戏。",
    "Behaviour": "行为",
    "Calendar": "日历",
    "Check Modifiers": "检查概览",
    "Cost:": "成本：",
    "Created by thepaperpilot and friends": "由 thepaperpilot 和朋友创建",
    "Cut down a tree every second": "每秒砍一棵树",
    "Cut down an additional tree per click": "每次点击砍一棵额外的树",
    "Cut down up to": "一次性砍倒",
    "Cut trees": "砍树",
    "Dyes": "染料",
    "Haley": "海莉",
    "Leafy Fingers": "多叶手指",
    "logs": "原木",
    "Modifiers": "概览",
    "NaN value detected!": "检测到 NaN 值！",
    "Nekosity": "恶毒",
    "Oil": "油",
    "Open Saves Manager": "打开保存管理器",
    "Paper": "纸",
    "Plant a tree every second": "每秒种一棵树",
    "Plant an additional tree per click": "每次点击额外种植一棵树",
    "Plant trees": "植树",
    "Plant up to": "植物高达",
    "Plastic": "塑料",
    "Present Packing": "礼物包装",
    "Presents": "礼物",
    "Reach": "达到",
    "Reindeer": "驯鹿",
    "Routing": "路由",
    "saplings": "树苗",
    "Sleigh Repair": "雪橇修理",
    "Special Thanks": "特别感谢",
    "Stop everything from moving.": "停止一切移动。",
    "Thanks for playing!": "感谢参与！",
    "The game is finished!": "游戏结束！",
    "The Modding Tree": "改装树",
    "The Paper Pilot Community": "论文试点社区",
    "Tip: You can hold down on actions to perform them automatically": "提示：您可以按住操作以自动执行它们",
    "to complete the day": "完成这一天",
    "total": "总计",
    "Wooden Fingers": "木手指",
    "trees": "树",
    "tree": "树",
    "/click": "/点击",
    "Base": "基础",
    "Total": "总计",
    "Trees give 25% more logs, and unlock more upgrades": "树木提供 25% 以上的原木，并解锁更多升级",
    "Smart Spades": "智能铲子",
    "Smart Knives": "智能刀具",
    "Sharper Fingers": "更锋利的手指",
    "Manually Plant trees twice as often": "手动植树的频率是原来的两倍",
    "Manually cut trees twice as often": "手动砍树的频率是原来的两倍",
    "Manual Cutting Amount": "手动砍伐数量",
    "Manual Planting Amount": "手动种植数量",
    "Manual Planting Cooldown": "手动种植冷却时间",
    "Manual Cutting Cooldown": "手动砍伐冷却时间",
    "Trees give 25% more logs, and unlock repeatable purchases": "树木提供 25% 以上的原木，并解锁可重复购买",
    "Each time you manually chop trees, gain 1s of automatic tree chopping production": "每次手动砍树，获得 1 秒的自动砍树产量",
    "Each time you manually plant trees, gain 1s of automatic tree planting production": "每次手动植树，获得1秒的自动植树产量",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Logs per Tree": "原木每棵树",
    "Add 10 trees to the forest": "向森林中添加 10 棵树",
    "Amount:": "数量:",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Auto Cutting Amount": "自动砍伐数量",
    "Auto Planting Amount": "自动种植数量",
    "Forest Size": "森林大小",
    "Expand Forest": "扩展森林",
    "Generic Cutters": "通用切割机",
    "Generic Planters": "通用种植机",
    "Generic Fingers": "通用手指",
    "Greener Fingers": "更环保的手指",
    "Each cutter cuts down 1 tree/s": "每个切割机每秒砍伐 1 棵树",
    "Each planter plants 0.5 trees/s": "每个种植机每秒种植 0.5 棵树",
    "Complete!": "完成！",
    "Day Complete!": "天数已完成！",
    "You can help continue the": "你可以继续帮助在",
    "Santa looks at all the wood you've gathered and tells you you've done well! He says you should take the rest of the day off so you're refreshed for tomorrow's work. Good Job!": "圣诞老人看着你收集的所有木头，告诉你你做得很好！ 他说你应该休息一天剩下的时间，这样你就可以精神焕发地迎接明天的工作。 干得不错！",
    "Game Paused": "游戏已暂停",
    "% completed": "% 已完成",
    "% of the foundation": "% 的地基",
    "Workshop": "车间",
    "Max Foundation": "最大地基",
    "Trees give 5% more logs for each % of foundation completed": "每完成 % 的地基，树木就会多提供 5% 的原木",
    "Show other completed milestones": "显示其他已完成的里程碑",
    "The foundation is": "地基 ",
    "Santa looked over your tree farm and was impressed with how much you could accomplish in just one day. Today's goal is to get a workshop built up for the elves to work in - and apparently, they need quite a lot of space to work!": "圣诞老人查看了您的林场，对您在短短一天内完成的工作印象深刻。 今天的目标是建造一个供精灵们工作的工坊——显然，他们需要相当大的空间来工作！",
    "Complete the foundation to complete the day": "完成地基以完成一天",
    "Build": "建造",
    "Milestone earned!": "获得里程碑！",
    "Cut an additional tree per second for each 5% of foundation completed": "每完成 5% 的地基，每秒多砍一棵树",
    "All automatic tree cutting is doubled": "所有自动砍树翻倍",
    "All automatic tree planting is doubled": "所有自动种树翻倍",
    "Log per tree is raised to the 1.2th power": "每棵树的原木提高到 1.2 次方",
    "Plant an additional tree per second for each 10% of foundation completed": "每完成 10% 的地基，每秒多种植一棵树",
    "The forest gains an extra tree for every 2% of foundation completed": "每完成 2% 的地基，森林就会获得一棵额外的树",
    "The workshop complete, Santa once again dismisses you for the day. With a strong foundation, this workshop should suffice for supporting future work toward this impossible mission. Good Job!": "车间完成了，圣诞老人再次放假。 有了坚实的地基，这个车间应该足以支持未来的工作来实现这个不可能的任务。 干得不错！",
    "Trees give twice as many logs": "树木提供两倍的原木",
    "With help from": "获得帮助从",
    "Workshop Complete!": "车间已完成！",
    "Ash": "灰烬",
    "Ash Gain": "灰烬增益",
    "Coal Gain": "煤增益",
    "Ash Soil": "灰烬泥土",
    "coal/sec": "煤/每秒",
    "logs/sec": "原木/每秒",
    "ash/sec": "灰烬/每秒",
    "Bigger Fires": "更大的火",
    "Bonfire": "篝火",
    "Bonfires": "篝火",
    "coal": "煤",
    "Currently:": "当前:",
    "Cut down twice as many trees/s": "砍伐两倍数量的树木/秒",
    "Cutters cut down trees": "切割机砍伐树木",
    "Dedicated Cutter Heaters": "专用切割机加热器",
    "Dedicated Planter Heaters": "专用种植机加热器",
    "Double the bonus from Fertilized Soil": "双倍的施肥土壤奖励",
    "Double the bonus from Heated Cutters": "双倍的加热切割机奖励",
    "Double the bonus from Heated Planters": "双倍的加热种植机奖励",
    "Efficient Fires": "高效火力",
    "Fertilized Soil": "施肥的土壤",
    "foundation progress": "基础进度",
    "Heated Cutters": "加热的切割机",
    "Heated Planters": "加热的种植机",
    "Log Consumption": "原木消耗",
    "Max": "最大",
    "More fertilizer helps trees grow bigger": "更多的肥料有助于树木长得更大",
    "Move the fires underground to keep the coal from turning to ash": "将火转移到地下以防止煤炭变成灰烬",
    "Mulched Soil": "覆盖的土壤",
    "Plant twice as many trees/s": "种植两倍的树木/秒",
    "Planters plant trees": "种植机种树",
    "Put all those fires together into a larger blaze": "把所有这些火放在一起变成更大的火焰",
    "Santa tells you that unfortunately there are quite a few naughty children out there this year, and he's going to need you to gather as much coal as you can for him to give out.": "圣诞老人告诉你，不幸的是，今年外面有很多顽皮的孩子，他需要你尽可能多地收集煤炭，以便他分发。",
    "Small Fire": "小火",
    "Small Fires": "小火",
    "small fires": "小火",
    "Trees give": "树给予",
    "Trees give 25% more logs": "树木多提供 25% 的原木",
    "Warmer Cutters": "保暖切割机",
    "Warmer Planters": "保暖种植机",
    "x faster": "x 更快",
    "x more logs": "x 更多原木",
    "ash": "灰烬",
    "Ashy Soil": "灰质土壤",
    "Even warmer cutters cut down trees faster": "更温暖的切割机砍伐树木的速度更快",
    "Even warmer planters plant trees faster": "更温暖的种植机种植树木的速度更快",
    "advent": "",
    "ure at:": "冒险在",
    "Santa looks at all the coal you've gathered and tells you you've done well! He says you should take the rest of the day off so you're refreshed for tomorrow's work. Good Job!": "圣诞老人看着你收集的所有煤炭并告诉你你做得很好！ 他说你应该休息一天剩下的时间，这样你就可以精神焕发地迎接明天的工作。 干得不错！",
    "Backspace": "退格键",
    "Black Dye Chambers": "黑色染色室",
    "Blue Dye Chambers": "蓝色染色室",
    "Breed sheep": "养殖绵羊",
    "Build foundation": "打地基",
    "By thepaperpilot and friends": "纸片飞行员和朋友们",
    "Charcoal Kiln": "木炭窑炉",
    "Charcoal Kilns": "木炭窑炉",
    "Forums": "论坛",
    "Green Dye Chambers": "绿色染色室",
    "Info": "信息",
    "Made in Profectus, by thepaperpilot with inspiration from Acameada and Jacorb": "在 Profectus 中由 thepaperpilot 制作，灵感来自 Acameada 和 Jacorb",
    "Orange Dye Chambers": "橙色染色室",
    "Process letters": "处理信件",
    "Purple Dye Chambers": "紫色染色室",
    "Red Dye Chambers": "红色染色室",
    "Select Box Maker": "选择制盒机",
    "Select Bucket Maker": "选择桶制造商",
    "Select Button Maker": "选择按钮制造商",
    "Select Circuit Board Manufacturer": "选择电路板制造商",
    "Select Cloth Shredder": "选择碎布机",
    "Select Cloth Warehouse": "选择布料仓库",
    "Select Clothes Maker": "选择服装制造商",
    "Select Conveyor": "选择传送带",
    "Select Cursor": "选择光标",
    "Select Delete": "选择删除",
    "Select Dye Warehouse": "选择染料仓库",
    "Select Game Console Maker": "选择游戏机制造商",
    "Select Metal Warehouse": "选择金属仓库",
    "Select Plastic Warehouse": "选择塑料仓",
    "Select Present Wrapper": "选择礼物包装",
    "Select Rotate Left": "选择向左旋转",
    "Select Rotate Right": "选择向右旋转",
    "Select Sawmill": "选择锯木厂",
    "Select Shovel and Pail Maker": "选择铲子和制桶机",
    "Select Shovel Maker": "选择铲子制造商",
    "Select Teddy Bear Maker": "选择泰迪熊制造商",
    "Select Thread Spinner": "选择线程微调器",
    "Select Trucks Maker": "选择卡车制造商",
    "Select Wheel Crafter": "选择车轮工匠",
    "Select Wood Warehouse": "选择木材仓库",
    "Select Wooden Block Maker": "选择木块机",
    "Shear sheep": "剪羊毛",
    "Spin wool": "纺羊毛",
    "White Dye Chambers": "白色染色室",
    "Yellow Dye Chambers": "黄色染色室",
    "Alright, it seems you finally have enough things set up to start bringing in the elves! Unfortunately, it seems they'll need to be retrained on how to help, since they've stopped practicing for 11 months!": "好吧，看来你终于准备好了足够的东西来开始引入精灵了！ 不幸的是，他们似乎需要重新接受如何提供帮助的培训，因为他们已经停止练习 11 个月了！",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "": "",
    "Logarithmic progress bars": "对数进度条",
    "Manual cutting and planting can happen twice as often for each trained elf": "对于每个受过训练的小精灵，人工砍树和种植的频率是原来的两倍",
    "Noel will automatically purchase fertilized soil you can afford, without actually spending any ash.": "诺埃尔 会自动购买你负担得起的施肥土壤，而无需实际花费任何灰烬。",
    "Noel": "诺埃尔",
    "Mary will automatically purchase heated planters you can afford, without actually spending any coal.": "玛丽会自动购买您负担得起的加热花盆，而无需实际花费任何煤炭。",
    "Mary": "玛丽",
    "Whether progress bars should be normalized for exponential growth.": "进度条是否应该针对指数增长进行标准化。",
    "Reach 6 trained elves and 1.00e9 coal to complete the day": "达到 6 个训练有素的精灵和 1.00e9 煤来完成这一天",
    "Holly": "霍莉",
    "Holly will automatically purchase cutters you can afford, without actually spending any logs.": "霍莉 会自动购买您负担得起的刀具，而无需实际花费任何原木。",
    "Hope": "霍普",
    "Hope will automatically purchase forest expanders you can afford, without actually spending any logs.": "霍普 会自动购买您负担得起的森林扩张器，而无需实际花费任何原木。",
    "Ivy": "艾维",
    "Ivy will automatically purchase planters you can afford, without actually spending any logs.": "艾维 会自动购买您负担得起的花盆，而无需实际花费任何原木。",
    "Jack": "杰克",
    "Jack will automatically purchase heated cutters you can afford, without actually spending any coal.": "杰克会自动购买你买得起的加热切割机，而无需实际花费任何煤炭。",
    "Training this elf will require resetting all your progress from days 1-3.": "训练这个精灵需要重置您第 1-3 天的所有进度。",
    "Elves": "精灵",
    "Hope Auto-Buy Frequency": "霍普 自动购买频率",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "lock": "lock",
    "": "",
    "": "",
    "": "",
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Factory": "工厂",
    "Management": "管理",
    "Set to ": "设为 ",
    "Research": "研究",
    "Last played ": "最近游戏 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/s average": "/秒 平均",
    "% Foundation Completed": "% 地基已完成",
    " elves": " 精灵",
    " Elf Trained": " 训练的精灵",
    " aren't reset after training": " 不会重置在训练后",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^TPS(.+)$/,
    /^天数(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Day (.+) Complete$/, '天数 $1 已完成'],
    [/^Burn (.+) logs for (.+) coal and (.+) ash$/, '燃烧 $1 原木，消耗 $2 煤炭和 $3 灰烬'],
    [/^equilibrium: \+(.+)\/s, limited by planting speed$/, '平衡：\+$1\/秒，受种植速度限制'],
    [/^equilibrium: \+(.+)\/s, limited by cutting speed$/, '平衡：\+$1\/秒，受砍伐速度限制'],
    [/^You've beaten Advent Incremental v(.+): Initial Commit$/, '您已经击败了 Advent Incremental v$1：初始提交'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^\+([\d\.]+)\/s$/, '\+$1\/秒'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Elves Trained$/, '$1 训练的精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);